#ifndef INC_JavaExpressionCompilerTokenTypes_hpp_
#define INC_JavaExpressionCompilerTokenTypes_hpp_
#include "third_party/antlr/lib/cpp/antlr/config.hpp"

ANTLR_BEGIN_NAMESPACE(devtools)
ANTLR_BEGIN_NAMESPACE(cdbg)
/* $ANTLR 2.7.2: "java_expression.g" -> "JavaExpressionCompilerTokenTypes.hpp"$ */
struct JavaExpressionCompilerTokenTypes {
	enum {
		EOF_ = 1,
		STATEMENT = 4,
		BINARY_EXPRESSION = 5,
		INSTANCEOF_BINARY_EXPRESSION = 6,
		UNARY_EXPRESSION = 7,
		PARENTHESES_EXPRESSION = 8,
		TYPE_CAST = 9,
		TYPE_NAME = 10,
		PRIMARY_SELECTOR = 11,
		DOT_SELECTOR = 12,
		METHOD_CALL = 13,
		EXPRESSION_LIST = 14,
		JNULL = 15,
		TRUE = 16,
		FALSE = 17,
		INSTANCEOF = 18,
		DOT = 19,
		HEX_NUMERIC_LITERAL = 20,
		OCT_NUMERIC_LITERAL = 21,
		FP_NUMERIC_LITERAL = 22,
		DEC_NUMERIC_LITERAL = 23,
		HexDigit = 24,
		DecDigit = 25,
		OctDigit = 26,
		NumericLiteral = 27,
		CharacterLiteral = 28,
		SingleCharacter = 29,
		StringLiteral = 30,
		StringCharacters = 31,
		StringCharacter = 32,
		EscapeSequence = 33,
		OctalEscape = 34,
		UnicodeEscape = 35,
		ZeroToThree = 36,
		Identifier = 37,
		LPAREN = 38,
		RPAREN = 39,
		LBRACE = 40,
		RBRACE = 41,
		LBRACK = 42,
		RBRACK = 43,
		SEMI = 44,
		COMMA = 45,
		ASSIGN = 46,
		CMP_GT = 47,
		CMP_LT = 48,
		BANG = 49,
		TILDE = 50,
		QUESTION = 51,
		COLON = 52,
		EQUAL = 53,
		CMP_LE = 54,
		CMP_GE = 55,
		NOTEQUAL = 56,
		AND = 57,
		OR = 58,
		ADD = 59,
		SUB = 60,
		MUL = 61,
		DIV = 62,
		BITAND = 63,
		BITOR = 64,
		CARET = 65,
		MOD = 66,
		SHIFT_LEFT = 67,
		SHIFT_RIGHT_S = 68,
		SHIFT_RIGHT_U = 69,
		WS = 70,
		COMMENT = 71,
		LINE_COMMENT = 72,
		NULL_TREE_LOOKAHEAD = 3
	};
};
ANTLR_END_NAMESPACE
ANTLR_END_NAMESPACE
#endif /*INC_JavaExpressionCompilerTokenTypes_hpp_*/
